### PR TITLE
update go-jsonnet

### LINKED ISSUE #128: Provide yaml serialization options for jsonnet engine
Currently the engine expects serialization to be done by Jsonnet itself. However, the yaml generated by [std.manifestYamlDoc](https://jsonnet.org/ref/stdlib.html#manifestYamlDoc) is a little heavy on quotation marks in the keys. It would be nice to let the user configure how to do serialization, and delegate to Go's serialization as an option.

Possible config options:

```
templates:
  engine: jsonnet
  serializationEngine: default # or `goyaml` 
```

### PR DESCRIPTION
**Pull request by Meroje**
This fixes #128 (in a way) thanks to jsonnet's 0.18 feature of removing the quotes.
Also, I had to update fsnotify as golang.org/x/sys would not compile on macos anymore.

https://github.com/google/jsonnet/releases/tag/v0.18.0

### CODE REVIEW

**Comment by jbrunton** [comment]
@Meroje: Nice! Thank you for the PR. I will review it this weekend.

**Comment by jbrunton** [comment]
Looks like some unrelated build issues, at least one of which is due to outdated dependency management. I'll fix on another branch.

**Comment by jbrunton** [comment]
@Meroje: I fixed the build issues on `develop`. Would you mind rebasing your branch?

The changes look good, I'll merge once the build passes. Thanks!

**Comment by Meroje** [comment]
sure :) thanks

**Comment by Meroje** [comment]
I think `statik` still has issues running, at least locally with act.

**Comment by jbrunton** [comment]
@Meroje: The build passed, so I merged your changes. I'll publish a release shortly.

Thanks for the contribution!

**Pull request merged**
